### PR TITLE
Catch delivery errors

### LINKED ISSUE #9: Catch delivery errors
When the Faraday adapter fails to deliver a message, the watch process may blow up.

Catch and log `Faraday::Error::ClientError`, and re-raise `CantDeliver`.

This should handle timeouts, SSL errors, DNS issues; and a test case should be provided for each.

### PR DESCRIPTION
**Pull request by mezis**
Closes #9.

Basically rescues from `Faraday::Error::ClientError`, which occurs on connection failures (can't resolve; can't connect; SSL fail; timeouts).

### CODE REVIEW

**Comment by rxbynerd** [comment]
do we need to require each `spec/support` in every spec or is it handled by RSpec for us?

LGTM :+1:

File: routemaster/services/deliver.rb [hunk 1]
```diff
@@ -36,9 +36,13 @@ def run
...
+        begin
+          response = _conn.post do |post|
+            post.headers['Content-Type'] = 'application/json'
+            post.body = data.to_json
+          end
+        rescue Faraday::Error::ClientError => e
+          raise CantDeliver.new("delivery failure (#{e.class.name}: #{e.message})")
         end
 
         if response.success?
```
Comment (rfonglip) [inline routemaster/services/deliver.rb:48]: If an error is caught, could response be nil?

Comment (rfonglip) [inline routemaster/services/deliver.rb:48]: Ah, looking at the faraday docs, it 
#Returns a Faraday::Response.

**Comment by mezis** [comment]
> do we need to require each spec/support in every spec or is it handled by RSpec for us?

We don't, but the convention in Routemaster is to be very explicit about _each_ depdendency, in _each_ source file.

Benefits: 
- speed. If your Guard runs one spec, and that spec only needs _some_ of the support, it'll run faster.
- bloat. When running the _watch_ process you don't need a lot of the code (controllers, for instance). Being explicit with _require_ means you alway load the exact minimum subset you need to run a particular process.

File: spec/support/webmock.rb [hunk 2]
```diff
@@ -0,0 +1,8 @@
+require 'rspec'
+require 'webmock/rspec'
+
+RSpec.configure do |config|
+  config.before(:each) { WebMock.enable! }
+  config.after(:suite) { WebMock.disable! }
```
Comment (levriero) [inline spec/support/webmock.rb:6]: What's the purpose of disabling webmock after the tests have ran?

File: spec/support/webmock.rb [hunk 3]
```diff
@@ -0,0 +1,8 @@
...
+end
+
```
Comment (levriero) [inline spec/support/webmock.rb:8]: Trailing EOF space

File: spec/support/webmock.rb (hunk 2 above)
Comment (mezis) [reply spec/support/webmock.rb:6]: This is because of the code coverage - after the suite runs, an upload to Code Climate will happen from within the process.

**Comment by levriero** [comment]
:shipit:
